version: "3.5"

services:

  redis:
    image: redis:6
    container_name: crmeb_redis
    restart: unless-stopped
    # Set maxmemory and policy, feel free to adjust
    command: "redis-server --maxmemory 1024mb --maxmemory-policy allkeys-lru"
    expose:
      - 6379
    networks:
      - service

  mysql:
    image: mariadb # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    container_name: crmeb_mysql
    expose:
      - 3306
    networks:
      - database
    command:
      [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "crmeb"
      MYSQL_USER: "crmeb"
      MYSQL_PASSWORD: "crmeb"
      MYSQL_ROOT_PASSWORD: "crmeb"
    restart: unless-stopped

  php-fpm:
    container_name: crmeb_php
    # image: registry.cn-shanghai.aliyuncs.com/elvin-docker/php4crmeb:7.4
    build: ./php
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    expose:
      - 20002
      - 20003
    tmpfs: /var/temp #上传临时文件夹
    working_dir: /var/www
    tty: true
    volumes:
      - ../CRMEB/crmeb:/var/www #程序运行目录
      - ../CRMEB/crmeb/runtime:/var/www/temp #程序缓存目录
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/conf.d:/usr/local/etc/php/conf.d
      - ./php/supervisor:/etc/supervisor
    networks:
      - application
      - service
      - database
    command:
      - /bin/sh
      - -c
      - |
        php think workerman start --d
        php think timer start --d
        /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
        php-fpm

  nginx:
    container_name: crmeb_nginx
    image: nginx
    restart: unless-stopped
    ports:
      - 28038:80
    depends_on:
      - php-fpm
    environment:
      TZ: Asia/Shanghai
    working_dir: /var/www
    volumes_from:
      - php-fpm
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites-available
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    networks:
      - application

  pma:
    container_name: crmeb_pma
    image: phpmyadmin/phpmyadmin
    restart: "no"
    ports:
      - 28039:80
    networks:
      - database
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: crmeb
      UPLOAD_LIMIT: 1024M

networks:
  application:
    driver: bridge
  service:
    driver: bridge
  database:
    driver: bridge
